/**
 * Cette procédure permet de réinitialiser l'ensemble des données présentes dans la table CIDEMIS_NOTICES
 * Elle peut-être appelé lors d'une MEP à la main
 * 
 * Exemple pour suivre son éxécution
 * DELETE FROM AUTORITES.CIDEMIS_NOTICES WHERE AUTORITES.CIDEMIS_NOTICES.PPN = '191473340';
 * SELECT * FROM AUTORITES.CIDEMIS_NOTICES WHERE PPN = '191473340';
 * INSERT INTO AUTORITES.CIDEMIS_NOTICES SELECT * FROM TABLE(AUTORITES.CIDEMIS_NOTICE_BY_PPN('191473340'));
 * SELECT * FROM DEMANDES WHERE PPN = '191473340';
 * SELECT * FROM DEMANDES WHERE ID_DEMANDE = '13141';
 * EXECUTE RESET_CIDEMIS_NOTICE;
 */
CREATE or REPLACE PROCEDURE RESET_CIDEMIS_NOTICE AS
  CURSOR ppn_rows IS SELECT * FROM DEMANDES;
BEGIN
  FOR DEM IN ppn_rows
  LOOP
    DELETE FROM AUTORITES.CIDEMIS_NOTICES WHERE AUTORITES.CIDEMIS_NOTICES.PPN = DEM.PPN;
    INSERT INTO AUTORITES.CIDEMIS_NOTICES SELECT * FROM TABLE(AUTORITES.CIDEMIS_NOTICE_BY_PPN(DEM.PPN));
  END LOOP;
END;