CREATE OR REPLACE TRIGGER UPDATE_NOTICE 
AFTER DELETE OR INSERT OR UPDATE OF PPN ON DEMANDES 
FOR EACH ROW
DECLARE
    leppn VARCHAR2(9);
BEGIN
    leppn := :new.PPN;
    delete from AUTORITES.CIDEMIS_NOTICES where AUTORITES.CIDEMIS_NOTICES.PPN = leppn;
    INSERT INTO AUTORITES.CIDEMIS_NOTICES SELECT * FROM TABLE(AUTORITES.CIDEMIS_NOTICE_BY_PPN(leppn)); 
END;